### ISSUE TITLE
デフォルトのpip が動かない && 最新版にしてもwarning が消えない

### ISSUE THREAD

**Issue by yomichi** [cmsi/MateriAppsLive#192]
少なくともMA 1.12 のデフォルトで、pip が動きません。

```bash
user@malive:~$ pip search pymatgen
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/search.py", line 34, in run
    pypi_hits = self.search(query, index_url)
  File "/usr/lib/python2.7/dist-packages/pip/commands/search.py", line 48, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1312, in single_request
    response.msg,
ProtocolError: <ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>

Storing complete log in /home/user/.pip/pip.log
```

バージョンは次の通り。

```bash
user@malive:~$ which pip
/usr/bin/pip
user@malive:~$ pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

見た感じものすごく古いので `sudo pip install -U pip` でアップグレードした後の結果は次の通り。

```bash
user@malive:~$ which pip
/usr/local/bin/pip
user@malive:~$ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
user@malive:~$ which pip
/usr/local/bin/pip
user@malive:~$ pip search pymatgen
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
pymatgen-db (0.7.0)         - Pymatgen-db is a database add-on for the Python
                              Materials Genomics (pymatgen) materials analysis
                              library.
pymatgen-diffusion (0.3.0)  - Add-on to pymatgen for diffusion analysis.
pymatgen-lammps (0.0.2)     - A LAMMPS wrapper using pymatgen
pymatgen (2017.8.14)        - Python Materials Genomics is a robust materials
                              analysis code that defines core object
                              representations for structures and molecules
                              with support for many electronic structure
                              codes. It is currently the core analysis code
                              powering the Materials Project
                              (https://www.materialsproject.org).
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

SSL のwarning が出ます。一応 install 自体は動きますが。
`sudo apt-get install python-urllib3` （もしくは、`sudo pip install urllib3[secure]`  ）をしても消えないので、python のversion を上げるのが一番手軽な気がします。

**Comment by wistaria** [comment]
古すぎますね。python-pip パッケージではなく get-pip.py を使うように修正します

**Comment by wistaria** [comment]
Stretch に上げることで解決できるはず
