### ISSUE TITLE
DCoreが動かない

### ISSUE THREAD

**Issue by wistaria** [cmsi/MateriAppsLive#303]
1. https://github.com/cmsi/MateriAppsLive/wiki/GettingStarted#dcore を実行すると `Input file does not exist.` というエラーになる
2. 入力ファイルを `dmft_square_ctseg.ini` に変更すると `dcore_pre` は通る。`dcore` は MPIエラーになる

**Comment by wistaria** [comment]
`square/work/sumkdft_Gloc/output` の内容は以下の通り
```
Starting run with 1 MPI rank(s) at : 2022-09-16 00:29:34.818495
Unexpected error: Type of indices incorrect : should be None, Gfindices, list of str, or list of list of str
Traceback (most recent call last):
  File "/usr/lib/python3.9/dist-packages/dcore/sumkdft_workers/mpi_main.py", line 20, in <module>
    runner.run()
  File "/usr/lib/python3.9/dist-packages/dcore/sumkdft_workers/gloc_worker.py", line 30, in run
    Gloc = sk.extract_G_loc(with_dc=with_dc)
  File "/usr/lib/python3.9/dist-packages/dcore/sumkdft_opt.py", line 264, in extract_G_loc
    G_loc_inequiv = [BlockGf(name_block_generator=[(block, GfImFreq(indices=inner, mesh=G_loc[0].mesh)) for block, inner in self.gf_struct_solver[ish].items()],
  File "/usr/lib/python3.9/dist-packages/dcore/sumkdft_opt.py", line 264, in <listcomp>
    G_loc_inequiv = [BlockGf(name_block_generator=[(block, GfImFreq(indices=inner, mesh=G_loc[0].mesh)) for block, inner in self.gf_struct_solver[ish].items()],
  File "/usr/lib/python3.9/dist-packages/dcore/sumkdft_opt.py", line 264, in <listcomp>
    G_loc_inequiv = [BlockGf(name_block_generator=[(block, GfImFreq(indices=inner, mesh=G_loc[0].mesh)) for block, inner in self.gf_struct_solver[ish].items()],
  File "/usr/lib/python3.9/dist-packages/triqs/gf/backwd_compat/gf_imfreq.py", line 73, in __init__
    delegate(self, **kw)
  File "/usr/lib/python3.9/dist-packages/triqs/gf/backwd_compat/gf_imfreq.py", line 66, in delegate
    super(GfImFreq, self).__init__(
  File "/usr/lib/python3.9/dist-packages/triqs/gf/gf.py", line 198, in __init__
    delegate(self, **kw)
  File "/usr/lib/python3.9/dist-packages/triqs/gf/gf.py", line 141, in delegate
    assert isinstance(indices, (type(None), list, GfIndices)), "Type of indices incorrect : should be None, Gfindices, list of str, or list of list of str"
AssertionError: Type of indices incorrect : should be None, Gfindices, list of str, or list of list of str
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[33525,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```
